### ISSUE TITLE
Waterfall chart cannot process negative value as expected

### ISSUE THREAD

**Issue by natee** [apache/incubator-echarts#11885]
### Version
4.5.0

### Reproduction link
[http://jsrun.pro/dtWKp/edit](http://jsrun.pro/dtWKp/edit)

### Steps to reproduce
originData = [-200,-120,-100,228,150,135,178,286,-119,-361,-203]

### What is expected?
It should handle negative value as excepted, 
eg: falling from 400 to -400, the bar should cross zero axis, total height is 800

![WX20191220-151604](https://user-images.githubusercontent.com/4928035/71237159-bc744300-233b-11ea-9215-ebf5dabe9145.png)

### What is actually happening?
When the value is falling from positive value to negative value, the bar is still above zero axis.

---
Relate issue #5308

**Comment by 100pah** [comment]
`stacked bar` does not support that mix positive and negative value.
Perhaps we can only use [custom series](https://echarts.apache.org/en/option.html#series-custom) to render this kind of diagram.

But should we support that specify the start points for each bar for this kind of scenario? 
For example,

```js
option = {
    xAxis: {},
    yAxis: {},
    series: [{
        bar: 'bar',
        encode: {
            x: 0,
            // When there are more than one dimensions specified on y,
            // the first dimension indicates the bar start, and the second 
            // indicates bar end.
            y: [1, 2] 
        },
        data: [
           //               bar start, bar end
            ['11-01',      55,            90],
            ['11-02',      65,           120],
            ['11-03',      75,           60],
            ['11-04',      85,           50]
        ]
    }]
}
```

**Comment by sjcobb** [comment]
@100pah adding a bar start and bar end feature would be very useful in both a waterfall and floating bar chart I've implemented that needs to account for bars that start as negative but end as positive.

**Comment by ataft** [comment]
Any updates on this TBD milestone? I just started implementing a waterfall chart and ran into this issue.

**Comment by sjcobb** [comment]
Not an ideal solution, but I gave up on using 'bar' series type for this and implemented it as a 'custom' chart type similar to [this example](https://echarts.apache.org/examples/en/editor.html?c=custom-profit) (see [renderItem docs](https://echarts.apache.org/en/option.html#series-custom.renderItem)). This means other features have to be re-implemented, but depending on your needs it might suffice. I can clean up the code and share it if you're interested.

**Comment by ataft** [comment]
That'd be great. I've created a waterfall with connecting lines and a total bar, but it still doesn't work if the yAxis goes below zero. Here's an example of what I created: https://codepen.io/ataft/pen/PojmzBL

**Comment by sjcobb** [comment]
Yeah no problem, [here is the src](https://github.com/sjcobb/echarts-waterfall/blob/master/waterfall.js) for the custom series type example and a[ live version link](https://sjcobb.github.io/echarts-waterfall/).

I used [dataset ](https://echarts.apache.org/en/option.html#dataset.source)to encode barStartValue and barEndValue, but that could be adjusted to not use dataset--the important part is how rectItem is constructed in [renderItem](https://echarts.apache.org/en/option.html#series-custom.renderItem). You'll also need to adjust tooltip and axis label [formatters](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter).

**Comment by helgasoft** [comment]
waterfall stacked bars are working in v.5.4.3 - [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiC8AEDaC0AmADMgNPAjCjnVsUQA41MBWdTAZjNIHYTiA2XTATgyqcwxSoF0A3AChgAZwCuAWxixkQ6JJnIRoCADopIAA4AKAG7RIAPmgBvRdOgBqGPsHRx09doliAFrqUBKBwF9vYWEAe20wAEtggDsjc2FoaAiwABsAUwAuOISEsFSADzBMgHIAdXBUgCcAMxBk5OgAYXcQCrAi-Og_NA68gEE88LFMizAAT20M6CKAY3KAc2CK0aK0aBABsQAZEAAjVOT0sw9ggHd0muSxVL9O7oTR_sHh246rivDUobgOhLMf7KiICkkyKAAVkiBpql3MFksBKit_jlxiCdi1EdlsmIINMANbFAAqwQgyQxmOg4VyUgAymM0sMkdkdot4RUGrDFsUwBUQFExNoWqkom07uSEtMORUuTy-QKKkK2oyuozUlJtM0xE8smKKVTaaN6dqddBmRVWezkpyptzefzBcKycaJZapdaZXb5Q7GQk_ErRZi1CBMk4pP6sTjcbSebk5qNirVSf9lZi_mLAcDioHHdkxhNimiKtmEtjIfipkSSUXFBGo_M41ME1XA8HwCBVoyIXsDkbycczokKhJUmHMdpgpqItFiuE-eF4e0xcnyZTVfrDRZnVbDCZzPKwBIKjF9Op9LUh8ZkNAAPxTfSRNJtaDFRa8uapIp-Jc-jr8YR-QRAA).

![image](https://github.com/apache/echarts/assets/13038071/8e7f3b95-f39a-4ae1-9ad0-8600b5ee6aff)
