### ISSUE TITLE
Is Echarts 3 responsive ?

### ISSUE THREAD

**Issue by AngryElephant** [apache/incubator-echarts#3990]
Im trying to switch from chartjs to Echarts.

Chartjs resize automatically when i resize the window by default which is not the case for Echarts. Is there any option for that ? 

Thank you.

**Comment by pissang** [comment]
You can use `chart.resize()` whenever the container size is changed

**Comment by hbthanki** [comment]
What if I have multiple charts on the page (inside panel/card) like dashboard? For example I have a panel. Inside panel body, I am showing a bar chart. Since I have specified fix height in px, chart.resize() will not cover the whole panel body. Is there a solution to get the height and width of panel?

**Comment by pissang** [comment]
@hbthanki Do you mean you fix the height of chart? If you have a flexible panel, don't fix the height of the chart. And resize() when panel changes the size.

**Comment by hbthanki** [comment]
Thanks for your reply. I got that working now. However, I have strange observation. If the container(panel)'s only width is changed, and I call .resize() nothing happens. But if I change height and width both and call resize(), chart is resizing properly.

**Comment by pissang** [comment]
`SVG` renderer or `Canvas` renderer ?

**Comment by hbthanki** [comment]
Yes I used svg renderer.

**Comment by pissang** [comment]
`SVG` renderer had this problem. Already fixed in https://github.com/ecomfe/zrender/pull/303

**Comment by hbthanki** [comment]
I have installed echarts from _npm i echarts_ just now. Do I need to refer any _branch_ for this change? Please bear with my little knowledge. And Thank you so much for your replies. I could find below code in echarts.js file: 
![image](https://user-images.githubusercontent.com/6187057/33726640-8c2b1b16-db43-11e7-8e95-78c2e5eb490e.png)

**Comment by pissang** [comment]
You need to checkout the latest code of [zrender](https://github.com/ecomfe/zrender) and put it under node_modules

**Comment by hbthanki** [comment]
1. Do I need to specifically import zrender? Because after _npm install zrender_ it is still not working. Either something wrong with my setup or I am missing some other lib?
2. curiosity question: Without installing zrender, and making _renderer: 'svg'_, it was creating svg. Why do we need extra lib for svg?
Thanks once again.
